### ISSUE TITLE
Pristine Build Error

### ISSUE THREAD

**Issue by spusuluri** [spusuluri/BME590_Lab7#1]
Mentioned that it might be with variable declaration in main source code

https://github.com/spusuluri/BME590_Lab7/blob/746671bf438e892cb441878829103da4430891ce/src/main.c#L1

**Comment by mlp6** [comment]
Your issue is: https://github.com/spusuluri/BME590_Lab7/blob/746671bf438e892cb441878829103da4430891ce/src/main.c#L119

You reference `&led`, but there is no GPIO pin struct initialized with that name.  Something like `&heartbeat_led` would work (something you have actually initialized).

**Comment by spusuluri** [comment]
Ok, I ran pristine build again and it was giving me this error: 

/Library/nordicsemi/Lab_07_Zephyr_Devicetree_GPIO_Callbacks/zephyr/include/zephyr/devicetree.h:230:32: error: 'DT_N_ALIAS_led4_P_gpios_IDX_0_VAL_pin' undeclared here (not in a function); did you mean 'DT_N_S_leds_S_led_4_P_gpios_IDX_0_VAL_pin'?

I am guessing I initialized the fifth LED incorrectly but don't know what exactly I did. Pushed most recent code.

**Comment by mlp6** [comment]
You are saying that you are using DT aliases, but for your LEDs, you are not: https://github.com/spusuluri/BME590_Lab7/blob/main/src/main.c#L15-19

`led0`, `led1`, etc. are not aliases according to your overlay file:
https://github.com/spusuluri/BME590_Lab7/blob/5094397ef5bda5626ab9b8d10c227fb6c74d52a4/nrf52833dk_nrf52833.overlay#L17-21

Your LED aliases are `heartbeat`, `buzzer`, etc.

**Comment by spusuluri** [comment]
Ok, that makes sense! It fixed the problem.
