### ISSUE TITLE
Error with Associating Callback

### ISSUE THREAD

**Issue by spusuluri** [spusuluri/BME590_Lab7#2]
When I pristine build, it says this 

../src/main.c: In function 'main':
/Library/nordicsemi/Lab_07_Zephyr_Devicetree_GPIO_Callbacks/blinky/src/main.c:124:29: error: 'sleep_cb' undeclared (first use in this function); did you mean 'sleep'?
  124 |         gpio_init_callback(&sleep_cb, sleep_callback, BIT(sleep.pin));
      |                             ^~~~~~~~

**Comment by mlp6** [comment]
You need to initialize the struct used to hold the callback, similar to how you initialize structs for the GPIO pins.  Something like this before `main()` is defined:

`static struct gpio_callback sleep_cb;`

I realized I failed to call that out in lecture.  Thanks for catching that.
